### ISSUE TITLE
How to transform the original data to the train data?

### ISSUE THREAD

**Issue by lisen0** [Determined22/zh-NER-TF#1]
Hi there,
I have some questions about the data preprocessing. I want to know how you transform the original data in data_path/original/train1.txt to the train data in data_path/train_data. Since some data in data_path/train_data do not exit in the train1.txt, like B-LOC, I want to know how you do that transform.
Thank you very much!

**Comment by Determined22** [comment]
Hi,
one character will be labelled with 'B-LOC' / 'B-PER' / 'B-ORG' if it is the beginning character of a location name / a person name / an organization name. Labels for non-beginning characters in entities are 'I-LOC' / 'I-PER' / 'I-ORG'.  'O' means that this character isn't a part of a named entity.
You could write a simple script for transforming :)

**Comment by Carbord** [comment]
您好，我想问下，上述提到的转换用的script具体是怎么写呢？新手，很多内容还很陌生，希望得到解答，谢谢~
