### ISSUE TITLE
tf1.2的支持问题

### ISSUE THREAD

**Issue by skywindy** [Determined22/zh-NER-TF#11]
在我的tf1.0版本的机器上可以正常运行，但是在我的tf1.2机器上报错
NotFoundError (see above for traceback): Key bi-lstm/bidirectional_rnn/fw/lstm_cell/kernel not found in checkpoint
请问怎么解决？

**Comment by knighter** [comment]
可参考： http://blog.csdn.net/lgh0824/article/details/77417848
兼容起来略麻烦， 最好是不要用之前的checkpoint，自己重新训练

**Comment by Determined22** [comment]
感谢楼上的解答。
有几个 issue 都说我的 checkpoint 不能直接用，我觉得应该是 TF 版本问题（我是在 Tensorflow 1.1 下训练的，版本升级之后好多地方都变了）。在本地重新训练一下吧。
ps: 迭代轮数我是顺手给的，应该加上 early stopping 。

**Comment by skywindy** [comment]
可以不用重新训练的，可以直接用这个checkpoint_convert.py将模型文件版本由tf1.1转为1.2就可以了
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/rnn/python/tools/checkpoint_convert.py

**Comment by git-mengmeng** [comment]
您好，您的新版无法下载，大概停在了21mb处，尝试了3次 ，好像不是网速的问题呢
