### ISSUE TITLE
Info：'perl' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by HWZX** [Determined22/zh-NER-TF#12]
Hi, I have a question that when I run the model as train mode, at the end of each epoch, it have a log
says that : 'perl' is not recognized as an internal or external command,operable program or batch file.

what does it mean

**Comment by HWZX** [comment]
I find the "perl" place, but I have another question that what's the code "conlleval_rev.pl" used for? Is it for calculate the precision, recall and FB1? If so why not code it in python?
thank you so much

**Comment by Determined22** [comment]
This is [an official evaluation tool](http://sighan.cs.uchicago.edu/bakeoff2006/). Please install perl in your PC to use this tool:)
