### ISSUE TITLE
关于运行的问题

### ISSUE THREAD

**Issue by git-mengmeng** [Determined22/zh-NER-TF#13]
刚拿到您的代码，准备好好学学一下，请问能告诉我一下正确的运行流程吗

**Comment by git-mengmeng** [comment]
Key bi-lstm/bidirectional_rnn/bw/lstm_cell/bias not found in checkpoint，在运行 test之后 出现了这个问题

请问 我该怎么结局呢

**Comment by Determined22** [comment]
我今天更新了模型文件（tf1.2），你可以试一下。

**Comment by git-mengmeng** [comment]
您好，您的新版无法下载，停在了21mb左右，下载3次 应该不是网速问题呢
