### ISSUE TITLE
What is the data set?

### ISSUE THREAD

**Issue by Jingyilang** [Determined22/zh-NER-TF#14]
Thanks for your code, it helps me l a lot. Can you tell me What is the data set in your code? Is it MSRA?

**Comment by git-mengmeng** [comment]
Hey，bro. Can you tell me how to run the main.py in the mode of test?

I just used the default data，but there were some errors in the console, like this
   **Key bi-lstm/bidirectional_rnn/bw/lstm_cell/bias not found in checkpoint**

my tensorflow is 1.6

**Comment by Determined22** [comment]
It looks like a portion of MSRA corpus. I present the statistics of the dataset in the README.md, FYR.
