### ISSUE TITLE
A question about word_embedding

### ISSUE THREAD

**Issue by HWZX** [Determined22/zh-NER-TF#15]
Hi, I have a question about _word_embedding that why you set it's trainable as True. In my opinion, the _word_embedding is used for mapping words to vector so that we can use it as the input of LSTM, why would the _word_embedding change while training?

thank you so much

**Comment by Determined22** [comment]
Word embedding matrix is trainable in neural network model. Generally, there are two common setting:
1. initialize it randomly, and update it during training
2. initialize it using pre-trained values, and update it or not according to the task you work on. 
For more information, you can refer to "Convolutional Neural Networks for Sentence Classification", 2014 EMNLP.
