### ISSUE TITLE
几点小疑问

### ISSUE THREAD

**Issue by mfxss** [Determined22/zh-NER-TF#30]
如果使用word2vec训练的词向量，不管改不改训练语料，都需要自己生成一个word2id.pkl文件，我这么理解对吗？
在训练的时候accuracy和precision分别是怎么算的？
一般词训练的过程中，没有把数字改成<NUM>训练的选项，为什么您会使用这种方法呢？效果会好么？

**Comment by Determined22** [comment]
Hi, 
1. word2id.pkl 是一个从"字"到"字的id"的映射(词典), 用于查询词向量矩阵. 如果词表变了, 就需要更新词典
2. 如果是问具体的计算方式, 以 precision 为例: 模型标注出的命名实体中正确的实体数量 / 模型标注出的命名实体数量
3. 我把所有的数字都替换成了统一的字符"NUM", 和普通的字一样看待, 不知道你问的是不是这个

**Comment by mfxss** [comment]
@Determined22 
谢谢您的回复，第一点我明白了，但是其他两点有些问题：
2.precision的计算方法我明白了。在evaluate时，输出既有一个accuracy，也有一个precision，他们的值是不同的，这两个有什么区别？
3.替换和不替换成NUM的效果哪一个好一点？

**Comment by wssgzxh** [comment]
我有个小问题，测试时显示的global_step是什么东东？
