### ISSUE TITLE
请问生成word2id文件时一直报错，要怎么解决呢？

### ISSUE THREAD

**Issue by newbirdhh** [Determined22/zh-NER-TF#39]
用的自己的语料训练的，标签只有两个‘T'和‘F'，但是总是有这个值不够的错误，请问要怎么解决呢？
 File "D:\npl\test_predata\data.py", line 154, in <module>
    vocab_build('D:/npl/test_predata/word2id.pkl','D:/npl/test_predata/data1.txt', 5)
  File "D:\npl\test_predata\data.py", line 40, in vocab_build
    data = read_corpus(corpus_path)
  File "D:\npl\test_predata\data.py", line 23, in read_corpus
    [char, label] = line.strip().split()
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by rorovic** [comment]
一样遇到这个问题

**Comment by bingoc0207** [comment]
> 用的自己的语料训练的，标签只有两个‘T'和‘F'，但是总是有这个值不够的错误，请问要怎么解决呢？
> File "D:\npl\test_predata\data.py", line 154, in 
> vocab_build('D:/npl/test_predata/word2id.pkl','D:/npl/test_predata/data1.txt', 5)
> File "D:\npl\test_predata\data.py", line 40, in vocab_build
> data = read_corpus(corpus_path)
> File "D:\npl\test_predata\data.py", line 23, in read_corpus
> [char, label] = line.strip().split()
> ValueError: not enough values to unpack (expected 2, got 1)

@xycim @rorovic @newbirdhh 您好 可以请教一下你们是怎么解决这个问题的吗
