### ISSUE TITLE
预测文本有时出现报错，UnboundLocalError local variable pre loc org referenced before assignment

### ISSUE THREAD

**Issue by nuaawqf** [Determined22/zh-NER-TF#44]
我随意用网上的一段新闻报道进行预测，这个错出现在调用util.py提取实体的函数时：
           33行 per += char
或者   56行 loc += char
或者   79行 org += char 
预测出来的tag是基本正确的，请问这个问题该怎么解决？

**Comment by hongqp** [comment]
utils.py

`def get_ORG_entity(tag_seq, char_seq):
    length = len(char_seq)
    ORG = []
    for i, (char, tag) in enumerate(zip(char_seq, tag_seq)):
        if tag == 'B-ORG':
            if 'org' in locals().keys():
                ORG.append(org)
                del org
            org = char
            if i+1 == length:
                ORG.append(org)
        if tag == 'I-ORG' and 'org' in locals().keys():
            org += char
            if i+1 == length:
                ORG.append(org)
        if tag not in ['I-ORG', 'B-ORG']:
            if 'org' in locals().keys():
                ORG.append(org)
                del org
            continue
    return ORG`
在变量使用前，加个判断即可。

**Comment by Bigchen8013** [comment]
> utils.py中，在变量使用前，加个判断即可。 下面是ORG的，其他同理。
> 
> ```python
> def get_ORG_entity(tag_seq, char_seq):
>     length = len(char_seq)
>     ORG = []
>     for i, (char, tag) in enumerate(zip(char_seq, tag_seq)):
>         if tag == 'B-ORG':
>             if 'org' in locals().keys():
>                 ORG.append(org)
>                 del org
>             org = char
>             if i+1 == length:
>                 ORG.append(org)
>         if tag == 'I-ORG' and 'org' in locals().keys():
>             org += char
>             if i+1 == length:
>                 ORG.append(org)
>         if tag not in ['I-ORG', 'B-ORG']:
>             if 'org' in locals().keys():
>                 ORG.append(org)
>                 del org
>             continue
>     return ORG
> ```

太强了  用了你的方法解决了   非常感谢
