### ISSUE TITLE
Missing B-LOC before I-LOC

### ISSUE THREAD

**Issue by rchen1207** [Determined22/zh-NER-TF#6]
I was trying to implement the demo mode with my own model, trained with own corpus. Unfortunately I got an error says:
```
============= demo =============
INFO:tensorflow:Restoring parameters from ./data_path_save/1513130611/checkpoints/model-560
Restoring parameters from ./data_path_save/1513130611/checkpoints/model-560
Please input your sentence:
马云
['I-LOC', 'I-LOC'] # print out the tags model predicts
Traceback (most recent call last):
  File "main.py", line 114, in <module>
    PER, LOC, ORG = get_entity(tag, demo_sent)
  File "/home/fanfan/py/nlp/ner/utils.py", line 16, in get_entity
    LOC = get_LOC_entity(tag_seq, char_seq)
  File "/home/fanfan/py/nlp/ner/utils.py", line 56, in get_LOC_entity
    loc += char
UnboundLocalError: local variable 'loc' referenced before assignment
```
It seems the cause is that I have `I-LOC` predicted without a `B-LOC` ahead of it. I thought LSTM+CRF is able to learn this information and knows that this is illegal. Any idea why this happened? 

Thank you.

**Comment by Determined22** [comment]
Hi, 
please check your output label sequence first. I think your corpus may have some wrong label sequences, which will result in this problem.

**Comment by rchen1207** [comment]
I checked my corpus and didn't find any illegal label sequences. If I understand correct, it should be fine as long as every `I-XXX` has a `B-XXX` (same name entity) ahead of it?

**Comment by Determined22** [comment]
The result given by my model is right:
============= demo =============
INFO:tensorflow:Restoring parameters from ./data_path_save/1499785642/checkpoints/model-95040
Restoring parameters from ./data_path_save/1499785642/checkpoints/model-95040
Please input your sentence:
幸冬梅
PER: ['幸冬梅']
LOC: []
ORG: []

What is the number of epochs you used? I guess that you used a smaller epochs. If your epochs is same to mine, I don't have any idea about this illegal output......

**Comment by rchen1207** [comment]
I guess not enough # of epoch might be the cause. I'll try with other settings, and report my results if anything positive returned. Thank you.
