### ISSUE TITLE
使用预训练word embedding的疑问

### ISSUE THREAD

**Issue by wssgzxh** [Determined22/zh-NER-TF#60]
您好，如果想用自己训练的ｗｏｒｄ　ｅｍｄｅｄｄｉｎｇ来训练模型，应该生成什么格式？是每行只有向量对吗？那顺序按照ｗｏｒｄ２ｉｄ里什么样的顺序排列？ｄｉｃｔ不是无序的吗？怎么对应？
然后，如果用预训练的词向量，在ｍｏｄｅｌ.ｐｙ中是不是要这么改？
１、parser.add_argument('--update_embedding', type=str2bool, default=True, help='update embedding during training')　　　　里的default是不是应该改成ｆａｌｓｅ？
parser.add_argument('--pretrain_embedding', type=str, default='random', help='use pretrained char embedding or init it randomly')　　ｄｅｆａｕｌｔ改成自己的地址？

**Comment by Determined22** [comment]
Hi,
1. word2id.pkl是键值对的形式，键是字，值是字对应的id。在word2id.pkl中，id是 x 的字需要出现在embedding matrix的第x行。
2. 我的代码里没有提供载入预训练embedding来训练模型的方式。需要自己修改下，可参考 #36 。
