### ISSUE TITLE
Test 验证的时候乱码

### ISSUE THREAD

**Issue by xuanzebi** [Determined22/zh-NER-TF#65]
测试验证的时候会有乱码...如下
![1541820583 1](https://user-images.githubusercontent.com/26642184/48297148-5ed8ba80-e4dc-11e8-8fc5-198218e0a35a.jpg)

**Comment by hipparic** [comment]
应该是字符编码问题，我通常都是转换为utf-8的编码格式。char = char.encode('utf-8').decode('utf-8')。

**Comment by xqtbox** [comment]
请问这个问题时怎么解决的？ 测试输出文件label_test 也是乱码

**Comment by ysgncss** [comment]
怎么解决的？
