### ISSUE TITLE
请问最后一层crf是完整的crf吗，还有特征函数吗，还是说只是一个viterbi解码

### ISSUE THREAD

**Issue by khuntoriia** [Determined22/zh-NER-TF#8]
你好，我刚接触这部分，看了您的博客过来的，这个问题困扰我很久，希望您可以帮忙解答。
在lstm输出得到k维的向量代表分类到这k个标签的概率之后，转移概率又是如何得到的呢？得到了转移概率的情况下是否可以直接用viterbi解码就够了，如果这样的话后接的这个并不是一个完整的CRF？
这里lstm是如何跟crf做衔接的？

**Comment by qujinqiang** [comment]
同样的疑问，还望作者能够回答；另外，我想问下，这个标注能不能把分词和命名实体一起做了？

**Comment by khuntoriia** [comment]
找到答案了，后接的CRF其实是有些变体的，但转移概率的思想还是属于CRF思想，转移矩阵是训练出来的，具体可以看我在知乎上的提问 https://www.zhihu.com/question/264394009

**Comment by qujinqiang** [comment]
@khuntoriia 兄好，看了知乎上面大神的回答；还是木有太明白；我的理解是CRF层其实就是一个viterbi解码过程，可以这样理解吗？  其中转移概率通过原始语料得到的

**Comment by khuntoriia** [comment]
感觉不能这样理解，如果我们不要CRF层，直接用LSTM的输出也是可以的，就是直接将每个位置的最高分对应的那个标签组合起来，但是这样会带来一个问题：可能结果会不符合我们的语言模型（例如，第一个位置我们选择得分最高的标签I-Person，第二个位置我们选择得分最高的标签I-Organization，这明显存在问题，I-P不可能会和I-O连起来用），所以我们需要加入我们语言模型的约束，也就是转移矩阵，这个转移矩阵和LSTM网络一样，最终都通过训练获取，模型训练完成之后，得到的转移矩阵其实就是我们提到的约束（可能在矩阵中I-P转移到I-O的概率很低很低，代表着我们更不倾向于这种用法），经过CRF层之后最终的得分将由两部分构成：LSTM输出的一元得分+转移得分，对于我们输入测试数据集时，需要用维特比解码来从中寻找到得分最高的序列路径。
还有，我不是兄，我是小姐姐

**Comment by qujinqiang** [comment]
哇喔，小姐姐这么厉害的，让人刮目相看；
转移矩阵在构建原始语料的时候，其实也能构建出来吧；这样的话，LSTM层输出直接加上viterbi解码不也就就算出了最佳路径；不过这块我还需要再细看下。
还有一些小问题，能方便加下小姐姐QQ之类的吗？
这是我的QQ：273459197
跪求小姐姐加下我

**Comment by Determined22** [comment]
小姐姐说的很全面了，我补充一点。LSTM-CRF的特点在于，对于一个句子中的一个位置，在训练的时候可以利用前一个位置的标注，来训练转移矩阵（可以把前一个位置的标注当作feature，这是不接CRF layer时做不到的）；测试的时候，用的是Viterbi算法来寻找得分最高的序列，那么后面位置的结果会起作用，这也是不接CRF layer时做不到的。

**Comment by Smile-shirley** [comment]
看了你们的讨论，还是不太明白这个转移矩阵是怎么来的，能再详细说下码？

**Comment by lijuable** [comment]
> 哇喔，小姐姐这么厉害的，让人刮目相看；
> 转移矩阵在构建原始语料的时候，其实也能构建出来吧；这样的话，LSTM层输出直接加上viterbi解码不也就就算出了最佳路径；不过这块我还需要再细看下。
> 还有一些小问题，能方便加下小姐姐QQ之类的吗？
> 这是我的QQ：273459197
> 跪求小姐姐加下我

你这个方式是理论方式，具体训练的时候是一起训练的，所以不会拆开
